import os, sys

from dotenv import load_dotenv
from requests import HTTPError
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import TextFormatter
from pathlib import Path
from bs4 import BeautifulSoup
import requests


load_dotenv()
HEADERS = os.getenv("YOUTUBE_TRANSCRIPT_API_KEY")
ROOT_DIR = Path(__file__).resolve().parents[0]


def get_topic(web: str) -> str:
    """
    Retrieve YouTube topic.
    If the topic doesn't exist, return its video code.
    """
    target_url = f"https://www.youtube.com/watch?v={web}"
    headers = {
        'User-Agent': HEADERS
    }
    response = requests.get(target_url, headers=headers)
    try:
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "lxml")
        meta_title = soup.find("meta", attrs={"name": "title"})["content"]
        return meta_title
    except HTTPError:
        return f"v={web}"

def retrieve_transcript(stored_dir, api, video_id):
    for _id in video_id:

        # Fetched_transcript = ytt_api.fetch("RwIspUe78Bg") # get whole transcript
        transcript_list = api.list(_id)

        formatter = TextFormatter()

        topic = get_topic(_id)
        save_file_path = stored_dir / f"{topic}.txt"

        for transcript in transcript_list:
            # print(
            #     f"Video_ID:{transcript.video_id}\n",
            #     f"Language:{transcript.language}\n",
            #     f"Language_code:{transcript.language_code}\n",
            #     # whether it has been manually created or generated by YouTube
            #     f"Is generated by Youtube:{transcript.is_generated}\n",
            #     # whether this transcript can be translated or not
            #     f"If this can be translated:{transcript.is_translatable}\n",
            #     # a list of languages the transcript can be translated to
            #     f"The languages that the transcript can be translated to:\n{transcript.translation_languages}\n",
            # )

            text_formatted = formatter.format_transcript(transcript.fetch())
            store_transcript(save_file_path, text_formatted)

def store_transcript(file_path, txt_format):
    with open(file=file_path, mode="w", encoding="utf-8") as txt_file:
        txt_file.write(txt_format.strip())
        print(f"{file_path} has been saved")


def main():
    """
    Retrieve the auto/manual CC transcript from YouTube and save it as a text file.
    """
    # Initialize the YouTube Transcript API to fetch video transcripts
    ytt_api = YouTubeTranscriptApi()
    video_id = sys.argv[1].strip().split(",")

    # Create a directory to store the transcript text file
    transcript_dir = Path(ROOT_DIR / "transcript")
    transcript_dir.mkdir(parents=True, exist_ok=True)

    # Retrieve the auto/manual CC transcript from YouTube and save it as a text file
    retrieve_transcript(transcript_dir, ytt_api, video_id)


if __name__ == "__main__":
    main()
